#!/bin/sh

BLITZEM_HOME=`dirname "$0"`/..

if [ "$(which java)" = "" ] ; then
    echo "Could not locate a system Java executable in \$PATH. Please ensure that Java is installed and try again.";
    exit 1;
fi

java -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n -jar $BLITZEM_HOME/lib/${project.artifactId}-${project.version}.jar $@